// GENERADO por generar_tuning_data.py - no editar a mano.
// Fuente: Assets/StreamingAssets/AOMigrator/SpellOverrides/spell_visual_tuning.json (2026-09-25)
window.AO_VISUAL_TUNING = {
  "version": "0.13.1",
  "entries": [
    {
      "spellId": 1,
      "projectileScale": 1.1,
      "impactScale": 1.25,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.571,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 2,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 3,
      "projectileScale": 1.1,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.714,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 4,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 5,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 6,
      "projectileScale": 1.1,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 11,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 12,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 13,
      "projectileScale": 1.0,
      "impactScale": 0.9,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.714,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 14,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 15,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 21,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 22,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 23,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 24,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 25,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.714,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 26,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 27,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 32,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 41,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 42,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.929,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 43,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 44,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 45,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 46,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 51,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 52,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 53,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 54,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 55,
      "projectileScale": 1.1,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.286,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 56,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.714,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 57,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 58,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 100,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 101,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 111,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 112,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.286,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 113,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 121,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 122,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 131,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 132,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 133,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.286,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 141,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.286,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 142,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 151,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 152,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 154,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 201,
      "projectileScale": 1.1,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 202,
      "projectileScale": 1.1,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 203,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 204,
      "projectileScale": 1.1,
      "impactScale": 1.25,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.571,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 205,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 206,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 207,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 208,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.929,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 209,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 210,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.929,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 211,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 213,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 214,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 215,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 216,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 217,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 218,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 219,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 220,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 221,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 229,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 231,
      "projectileScale": 1.0,
      "impactScale": 0.8,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.071,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 234,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 236,
      "projectileScale": 1.0,
      "impactScale": 0.65,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.2,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 237,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.28,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 242,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.143,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 243,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 244,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.143,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 245,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 246,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 0.9,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.143,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 248,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 249,
      "projectileScale": 1.0,
      "impactScale": 1.1,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 250,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 251,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 252,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 253,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 254,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 255,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 256,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 0.65,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 257,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 258,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 259,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 260,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 261,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 262,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 263,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 264,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 265,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 266,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 267,
      "projectileScale": 1.25,
      "impactScale": 1.1,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.429,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 268,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.143,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 269,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 1.143,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 270,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 271,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 272,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 273,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 274,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 275,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 276,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 277,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 278,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 279,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 280,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 281,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 282,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 283,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 284,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.1,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 285,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 286,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 287,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 288,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 289,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 290,
      "projectileScale": 1.0,
      "impactScale": 1.0,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.35,
      "persistentFps": 8.0,
      "transientFps": 14.0
    },
    {
      "spellId": 291,
      "projectileScale": 1.1,
      "impactScale": 1.25,
      "persistentScale": 1.0,
      "projectileYOffset": 0.35,
      "impactYOffset": 0.25,
      "persistentYOffset": 0.25,
      "projectileSpeed": 18.0,
      "impactDuration": 0.571,
      "persistentFps": 8.0,
      "transientFps": 14.0
    }
  ]
};
window.AO_VISUAL_TUNING_META = {"source": "Assets/StreamingAssets/AOMigrator/SpellOverrides/spell_visual_tuning.json", "generated": "2026-09-25", "sha1": "8addf0da576f74af48fbfa37da03b07e0e4ffa99", "entries": 122, "floatFields": ["projectileScale", "impactScale", "persistentScale", "projectileYOffset", "impactYOffset", "persistentYOffset", "projectileSpeed", "impactDuration", "persistentFps", "transientFps"], "intFields": ["spellId"], "indent": 2, "eol": "\n", "trailingNewline": false};
window.AO_SKILLSHOT_VISUAL = {"source": "Assets/StreamingAssets/AOMigrator/SpellOverrides/skillshot_tuning.json", "note": "solo visualScale (Arte); speed/range/hitRadius son gameplay y no se incluyen", "entries": {"1": 1.0, "2": 1.0, "3": 1.0, "6": 1.0, "43": 1.0, "55": 1.0, "201": 1.0, "202": 1.0, "204": 1.0, "205": 1.0, "209": 1.0, "211": 1.0, "267": 1.0, "291": 1.0}, "version": "0.26.7"};
